---
ID: "63eb7f46-ede1-4a7d-a4a9-0e9945caf32a"
Parent: "e40dbaaa-bbb0-4583-b871-af7acf2d6e71"
Template: "f0369e1a-9030-4a05-a09c-ef09b664ed27"
Path: /sitecore/content/ARM/Global/Media/Product1
DB: master
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160112T161038Z
    - ID: "4ff62b0a-d73b-4436-bea2-023154f2ffc4"
      Hint: MediaThumbnail
      Value: |
        <image mediapath="" src="" height="" mediaid="{2F3504A7-DA19-42CE-8985-6A5DC110F52E}" hspace="" usethumbnail="" showineditor="" width="" alt="Woman on Phone" vspace="" ></image>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "9f51dead-ad6e-41c2-9759-7be17eb474a4"
      Hint: MediaImage
      Value: |
        <image mediapath="" src="" height="" mediaid="{2F3504A7-DA19-42CE-8985-6A5DC110F52E}" hspace="" usethumbnail="" showineditor="" width="" alt="Woman on Phone" vspace="" />
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150901T054400Z
    - ID: "302c9f8d-f703-4f76-a4ab-73d222648232"
      Hint: MediaDescription
      Value: Change and add quickly and without worry
    - ID: "4ff62b0a-d73b-4436-bea2-023154f2ffc4"
      Hint: MediaThumbnail
      Value: |
        <image mediapath="" src="" height="" mediaid="{2F3504A7-DA19-42CE-8985-6A5DC110F52E}" hspace="" usethumbnail="" showineditor="" width="" alt="Woman on Phone" vspace="" ></image>
    - ID: "63dda48b-b0cb-45a7-9a1b-b26ddb41009b"
      Hint: MediaTitle
      Value: Product1
    - ID: "9f51dead-ad6e-41c2-9759-7be17eb474a4"
      Hint: MediaImage
      Value: |
        <image mediapath="" src="" height="" mediaid="{CBE08312-E390-4ADD-A225-3EA48CFCCBFF}" hspace="" usethumbnail="" showineditor="" width="" alt="Woman on Phone" vspace="" />
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170323T054657Z
    - ID: "302c9f8d-f703-4f76-a4ab-73d222648232"
      Hint: MediaDescription
      Value: 変更と迅速かつ心配なしで追加
    - ID: "4ff62b0a-d73b-4436-bea2-023154f2ffc4"
      Hint: MediaThumbnail
      Value: |
        <image mediapath="" src="" height="" mediaid="{2F3504A7-DA19-42CE-8985-6A5DC110F52E}" hspace="" usethumbnail="" showineditor="" width="" alt="Woman on Phone" vspace="" ></image>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "63dda48b-b0cb-45a7-9a1b-b26ddb41009b"
      Hint: MediaTitle
      Value: Flexibility
    - ID: "9f51dead-ad6e-41c2-9759-7be17eb474a4"
      Hint: MediaImage
      Value: |
        <image mediapath="" src="" height="" mediaid="{2F3504A7-DA19-42CE-8985-6A5DC110F52E}" hspace="" usethumbnail="" showineditor="" width="" alt="Woman on Phone" vspace="" />
